### ISSUE TITLE
Window is not defined after upgrading to v3

### ISSUE THREAD

**Issue by fuzunspm** [gregnb/mui-datatables#1368]
## Current Behavior
After upgrading to v3 none of my mui datatables pages are working. Here is the error output:

```
ReferenceError: window is not defined
    at t.value (/node_modules/mui-datatables/dist/index.js:1:95150)
    at processChild (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at render (/node_modules/next/dist/next-server/server/render.js:3:298)
    at Object.renderPage (/node_modules/next/dist/next-server/server/render.js:46:1020)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:133:19)
    at loadGetInitialProps (/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/node_modules/next/dist/next-server/server/render.js:46:1330)
    at async /node_modules/next/dist/next-server/server/next-server.js:68:285
    at async /node_modules/next/dist/next-server/server/next-server.js:67:142
    at async DevServer.renderToHTMLWithComponents (/node_modules/next/dist/next-server/server/next-server.js:91:254)
    at async DevServer.renderToHTML (/node_modules/next/dist/next-server/server/next-server.js:92:254)
    at async DevServer.renderToHTML (/node_modules/next/dist/server/next-dev-server.js:22:539)
    at async DevServer.render (/node_modules/next/dist/next-server/server/next-server.js:48:236)
    at async Object.fn (/node_modules/next/dist/next-server/server/next-server.js:35:852)
    at async Router.execute (/node_modules/next/dist/next-server/server/router.js:28:28)
    at async DevServer.run (/node_modules/next/dist/next-server/server/next-server.js:44:494)
    at async DevServer.handleRequest (/node_modules/next/dist/next-server/server/next-server.js:13:133)
```

## Your Environment

| Tech         | Version |
|--------------|---------|
| Material-UI  |     4.10.2    |
| MUI-datatables  |     3.1.2    |
| React        |     16.13.1    |
| browser      |     Firefox/Safari    |

**Comment by patorjk** [comment]
3.0.1 should work.

I'm assuming you're doing server-side rendering? I created a beta version which I think will resolve the issue. Can you try it out and let me know:

npm install mui-datatables@3.1.3-beta.0

If it works I'll publish it as a patch tonight.

**Comment by fuzunspm** [comment]
3.1.3-beta.0 worked! thank you very much

**Comment by patorjk** [comment]
Sounds good thank you for the report! I'll push version 3.1.3 tonight.

**Comment by jdwilemo** [comment]
This issue seems to be back, tested in 3.7.8+ on up to latest, related to the same use case of server side rendering. 
Any thoughts @patorjk ?

Here's a snippit from the log
![image](https://user-images.githubusercontent.com/6248710/140263335-cee4094f-c3a0-48c5-854e-e8bae23bd053.png)
