### ISSUE TITLE
OnRowClick navigate to details page and on returning back its not landing on same paginated page

### ISSUE THREAD

**Issue by krsandesh** [gregnb/mui-datatables#781]
Hi Team,

I have enabled pagination and i am on page 2 (each page shows 5 rows).
OnRowClick i am navigating to different page and showing more details on that specific row, when i navigate back its landing on page 1.

I am using this.props.history.goBack(); to navigate back.

How can i achieve to navigate back to the same paginated page ?

Tech	Version
Material-UI	4.0.1
MUI-datatables	2.5.1
React	16.8.6
browser	chrome
etc

**Comment by gabrielliwerant** [comment]
If `this.props.history.goBack()` triggers a re-render of the component, then you should be able to re-initialize the value in a lifecycle function like `componentDidMount` or `constructor`. If not, then I would look to see if there's a way to determine that page navigation took place, and reset the value on that condition instead.

**Comment by krsandesh** [comment]
> If `this.props.history.goBack()` triggers a re-render of the component, then you should be able to re-initialize the value in a lifecycle function like `componentDidMount` or `constructor`. If not, then I would look to see if there's a way to determine that page navigation took place, and reset the value on that condition instead.

If i use lifecycle methods that will reset my state and hence that is out of option, using OnTableChange i am getting the table details but the problem is when i navigate back to this page after onrowclick i will lose all the information. Can we some one add the page details to history ?

**Comment by gabrielliwerant** [comment]
I think I need more information about this to be more helpful. Can you provide a codesandbox example?

**Comment by krsandesh** [comment]
@gabrielliwerant i tried to resolve my case by using Dialog react material ui component :) ..

**Comment by gabrielliwerant** [comment]
Oh great, so you got it working? If so, maybe copying an example here would help others if they run into a similar issue.

**Comment by Sara-chi** [comment]
Hi! I have a similar issue to this and maybe you can help me with this? We, too, navigate to a different site onRowClick and on return we would like to load the same page in the grid (a.k.a where we left of).

I got this to work, kind of? But there is a warning in the debugging console...

What I did is save the currentPage in our redux-store and then use that for `options: page (number)`. It works just fine on page: 0 but trows this warning on any other page, even if that page exists:

```
Current page is out of range, using the highest page that is in range instead. 
    at n (https://localhost/static/js/1.chunk.js:218185:5)
    at WithStyles (https://localhost/static/js/1.chunk.js:180054:31)
    at table
    at Table (https://localhost/static/js/1.chunk.js:27870:23)
    at WithStyles (https://localhost/static/js/1.chunk.js:180054:31)
    at https://localhost/static/js/1.chunk.js:230075:23
    at div
    at div
    at Paper (https://localhost/static/js/1.chunk.js:19930:23)
    at WithStyles (https://localhost/static/js/1.chunk.js:180054:31)
    at a (https://localhost/static/js/1.chunk.js:220551:5)
    at WithStyles (https://localhost/static/js/1.chunk.js:180054:31)
    at Transition (https://localhost/static/js/1.chunk.js:265340:30)
    at Slide (https://localhost/static/js/1.chunk.js:22842:24)
    at ThemeProvider (https://localhost/static/js/1.chunk.js:178758:24)
    at FullGrid (https://localhost/static/js/main.chunk.js:3950:73)
    at div
    at StyledComponent (https://localhost/static/js/1.chunk.js:179827:28)
    at HiddenJs (https://localhost/static/js/1.chunk.js:13285:24)
    at WithWidth(HiddenJs) (https://localhost/static/js/1.chunk.js:37542:90)
    at Hidden (https://localhost/static/js/1.chunk.js:12940:37)
    at SearchGrid (https://localhost/static/js/main.chunk.js:4579:17)
    at Route (https://localhost/static/js/1.chunk.js:263312:29)
    at Switch (https://localhost/static/js/1.chunk.js:263514:29)
    at div
    at Container (https://localhost/static/js/1.chunk.js:7284:23)
    at WithStyles (https://localhost/static/js/1.chunk.js:180054:31)
    at ContentContainer (https://localhost/static/js/main.chunk.js:895:17)
    at main
    at div
    at ThemeProvider (https://localhost/static/js/1.chunk.js:178758:24)
    at Main (https://localhost/static/js/main.chunk.js:1513:17)
    at Router (https://localhost/static/js/1.chunk.js:262947:30)
    at BrowserRouter (https://localhost/static/js/1.chunk.js:262567:35)
    at CookiesProvider (https://localhost/static/js/1.chunk.js:227698:24)
    at App (https://localhost/static/js/main.chunk.js:28:81)
    at Provider (https://localhost/static/js/1.chunk.js:260890:20)
```

I am assuming the problem is, that it first sets the page and then load the data. (Both is present from the beginning, there is no data that needs to be loaded async or anything)
Since the page is displayed correctly, this doesn't seem to be a big issue. But is this the right way to go or is there a better/correct way to set the current page?
What I am trying to ask: Did I do something wrong or is this a minor bug? :)

Tech version:
Material-UI: 4.11.0
MUI-datatables: 3.4.1
React: 16.13.1
browser: chrome

**Comment by patorjk** [comment]
@Sara-chi if you create a codesandbox I'll take a look.

The warning comes from this line: https://github.com/gregnb/mui-datatables/blob/master/src/components/TableBody.js#L79

Is the page displaying correctly with the correct data?

**Comment by Sara-chi** [comment]
@patorjk Thanks for the reply!

The page is displaying correctly and with the correct data. There is literally just a warning in the debug console - two of them at a time.

I did make [this sandbox](https://codesandbox.io/s/stupefied-goldwasser-65tjd?file=/src/SearchGrid.js), but there it's not throwing a warning for whatever reason. So, my issue has most likely nothing to do with mui-datatables, since it works just fine in a smaller example. Yay! :)
If you have any idea what might be causing this, I'd appriciate the input! But thanks so far anyways!
